# Include base configuration
source-file ~/.config/tmux/base.conf

# Set to tmux* for 256 color support (also keeps home/end working)
if-shell '[ -f /etc/unraid-version ]' {
  set -s default-terminal "xterm-256color"
} {
  set -s default-terminal "tmux-256color"
}

# Open tmux sessions
bind C-j display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"

# ╓───── tokyo-night-tmux
# ╙────────────────────────────────────── ─ ─

set -g @tokyo-night-tmux_transparent 1
set -g @tokyo-night-tmux_show_hostname 1
set -g @tokyo-night-tmux_show_datetime 1
set -g @tokyo-night-tmux_time_format 12H
set -g @tokyo-night-tmux_date_format hide
set -g @tokyo-night-tmux_show_netspeed 1
set -g @tokyo-night-tmux_netspeed_showip 1
set -g @tokyo-night-tmux_show_git 0

# ╓───── Tmux Plugin Manager
# ╙────────────────────────────────────── ─ ─

# Automatic tpm installation
# https://github.com/tmux-plugins/tpm/blob/master/docs/automatic_tpm_installation.md
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# List of plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "joshmedeski/tmux-nerd-font-window-name"
set -g @plugin 'jaclu/tmux-menus'
set -g @plugin "janoamaral/tokyo-night-tmux"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run "~/.tmux/plugins/tpm/tpm"
